name: "core: publish (rxdiffadapter)"

on:
  release:
    types: [published]

jobs:
  publish-bintray:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/rxdiffadapter')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :rxdiffadapter:bintrayUpload -PdryRun=false
        env:
          BINTRAY_USER: yatsinar
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}